### ISSUE TITLE
de kleine gele rondjes met cijfertjes misschien iets meer van de zijkant af 

### ISSUE THREAD

**Issue by anoukbruinn** [iBadr49/performance-vinimini#22]
dan zou je ook bijvoorbeeld de plek van stap 1 iets naar rechts moeten verplaatsen

**Comment by Daniquedejong** [comment]
Hier hebben we ook naar gekeken. We twijfelen heel erg hierover, maar we laten het staan, omdat we feedback van de opdrachtgever willen hierover.
